---
url: https://github.com/eugeneljt/lt2ha-ljt
name: "Larnitech to Home Assistant Bridge"
slug: "lt2ha"
version: "1.1.0-ljt.7"
description: "Bridge between Larnitech and Home Assistant using WebSockets and MQTT"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  ha_mqtt_discovery_prefix: "homeassistant"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "mosquitto"
  mqtt_password: ""
  mqtt_proto: "4"
  mqtt_transport: "tcp"
  lt_host: ""
  lt_port: 2041
  lt_key: ""
  lt_ignore_addr: []
  lt_ignore_type:
    - com-port
  lt_ignore_area:
    - Setup
  lt_cleanup_legacy_sensor_addrs:
    - "15:23"
    - "15:22"
    - "15:24"
    - "15:25"
  restart_attempts: 5
  restart_delay: 5
schema:
  ha_mqtt_discovery_prefix: "str"
  mqtt_host: "str"
  mqtt_port: "port"
  mqtt_username: "str"
  mqtt_password: "password"
  mqtt_proto: "list(3|4|5)"
  mqtt_transport: "list(tcp|websockets|unix)"
  lt_host: "str"
  lt_port: "port"
  lt_key: "password"
  lt_ignore_addr:
    - str?
  lt_ignore_type:
    - str?
  lt_ignore_area:
    - str?
  lt_cleanup_legacy_sensor_addrs:
    - str?
  restart_attempts: "int(0,10)"
  restart_delay: "int(3,20)"
